### PR TITLE
Ralberd patch 1

### PR DESCRIPTION
**Pull request by ralberd**
Testing out a format check action that would run on a PR.

### CODE REVIEW

**Comment by ralberd** [comment]
I'm not sure why this action is failing. It doesn't have any helpful output. I'll keep trying things...

**Comment by rawildman** [comment]
> I'm not sure why this action is failing. It doesn't have any helpful output. I'll keep trying things...

Clang version maybe?

**Comment by ralberd** [comment]
Letting it set clang version to the default doesn't seem to help

**Comment by ralberd** [comment]
Not taking this approach any longer

**Pull request closed without merging**
